// @Name: HL7 V3 aliases (complete)
// @Description: Aliases for all V3 code systems defined at https://terminology.hl7.org/codesystems.html. Generated 2021-07-13 13:28:48 by https://github.com/FHIR/FSHOnline-Examples/tree/main/Scripts/Aliases/HL7.ipynb. Leading $ signs are optional but are useful for visually distinguishing aliases from other names.

Alias:   $v3-AcknowledgementCondition            = http://terminology.hl7.org/CodeSystem/v3-AcknowledgementCondition              // AcknowledgementCondition
Alias:   $v3-AcknowledgementDetailCode           = http://terminology.hl7.org/CodeSystem/v3-AcknowledgementDetailCode             // AcknowledgementDetailCode
Alias:   $v3-AcknowledgementDetailType           = http://terminology.hl7.org/CodeSystem/v3-AcknowledgementDetailType             // AcknowledgementDetailType
Alias:   $v3-AcknowledgementType                 = http://terminology.hl7.org/CodeSystem/v3-AcknowledgementType                   // AcknowledgementType
Alias:   $v3-ActClass                            = http://terminology.hl7.org/CodeSystem/v3-ActClass                              // ActClass
Alias:   $v3-ActCode                             = http://terminology.hl7.org/CodeSystem/v3-ActCode                               // ActCode
Alias:   $v3-ActExposureLevelCode                = http://terminology.hl7.org/CodeSystem/v3-ActExposureLevelCode                  // ActExposureLevelCode
Alias:   $v3-ActInvoiceElementModifier           = http://terminology.hl7.org/CodeSystem/v3-ActInvoiceElementModifier             // ActInvoiceElementModifier
Alias:   $v3-ActMood                             = http://terminology.hl7.org/CodeSystem/v3-ActMood                               // ActMood
Alias:   $v3-ActPriority                         = http://terminology.hl7.org/CodeSystem/v3-ActPriority                           // ActPriority
Alias:   $v3-ActReason                           = http://terminology.hl7.org/CodeSystem/v3-ActReason                             // ActReason
Alias:   $v3-ActRelationshipCheckpoint           = http://terminology.hl7.org/CodeSystem/v3-ActRelationshipCheckpoint             // ActRelationshipCheckpoint
Alias:   $v3-ActRelationshipJoin                 = http://terminology.hl7.org/CodeSystem/v3-ActRelationshipJoin                   // ActRelationshipJoin
Alias:   $v3-ActRelationshipSplit                = http://terminology.hl7.org/CodeSystem/v3-ActRelationshipSplit                  // ActRelationshipSplit
Alias:   $v3-ActRelationshipSubset               = http://terminology.hl7.org/CodeSystem/v3-ActRelationshipSubset                 // ActRelationshipSubset
Alias:   $v3-ActRelationshipType                 = http://terminology.hl7.org/CodeSystem/v3-ActRelationshipType                   // ActRelationshipType
Alias:   $v3-ActSite                             = http://terminology.hl7.org/CodeSystem/v3-ActSite                               // ActSite
Alias:   $v3-ActStatus                           = http://terminology.hl7.org/CodeSystem/v3-ActStatus                             // ActStatus
Alias:   $v3-ActUSPrivacyLaw                     = http://terminology.hl7.org/CodeSystem/v3-ActUSPrivacyLaw                       // ActUSPrivacyLaw
Alias:   $v3-ActUncertainty                      = http://terminology.hl7.org/CodeSystem/v3-ActUncertainty                        // ActUncertainty
Alias:   $v3-ada-snodent                         = http://www.ada.org/snodent                                                     // Systematized Nomenclature of Dentistry (SNODENT)
Alias:   $v3-AddressPartType                     = http://terminology.hl7.org/CodeSystem/v3-AddressPartType                       // AddressPartType
Alias:   $v3-AddressUse                          = http://terminology.hl7.org/CodeSystem/v3-AddressUse                            // AddressUse
Alias:   $v3-AdministrativeGender                = http://terminology.hl7.org/CodeSystem/v3-AdministrativeGender                  // AdministrativeGender
Alias:   $v3-AmericanIndianAlaskaNativeLanguages = http://terminology.hl7.org/CodeSystem/v3-AmericanIndianAlaskaNativeLanguages   // AmericanIndianAlaskaNativeLanguages
Alias:   $v3-brazilianProcedureCodesSUS          = http://terminology.hl7.org/CodeSystem/v3-brazilianProcedureCodesSUS            // Brazilian Procedure Codes SUS
Alias:   $v3-cci                                 = http://cihi.ca/fhir/CodeSystem/cihi-cci                                        // Canadian Classification of Health Interventions
Alias:   $v3-Calendar                            = http://terminology.hl7.org/CodeSystem/v3-Calendar                              // Calendar
Alias:   $v3-CalendarCycle                       = http://terminology.hl7.org/CodeSystem/v3-CalendarCycle                         // Calendar Cycle Codes
Alias:   $v3-CalendarType                        = http://terminology.hl7.org/CodeSystem/v3-CalendarType                          // CalendarType
Alias:   $v3-Charset                             = http://terminology.hl7.org/CodeSystem/v3-Charset                               // Charset
Alias:   $v3-CodeSystem                          = http://terminology.hl7.org/CodeSystem/v3-CodeSystem                            // CodeSystem
Alias:   $v3-CodeSystemType                      = http://terminology.hl7.org/CodeSystem/v3-CodeSystemType                        // HL7 Code System Type
Alias:   $v3-CodingRationale                     = http://terminology.hl7.org/CodeSystem/v3-CodingRationale                       // CodingRationale
Alias:   $v3-CommunicationFunctionType           = http://terminology.hl7.org/CodeSystem/v3-CommunicationFunctionType             // CommunicationFunctionType
Alias:   $v3-CompressionAlgorithm                = http://terminology.hl7.org/CodeSystem/v3-CompressionAlgorithm                  // CompressionAlgorithm
Alias:   $v3-ConceptCodeRelationship             = http://terminology.hl7.org/CodeSystem/v3-ConceptCodeRelationship               // Possible Concept Code Relationships
Alias:   $v3-ConceptGenerality                   = http://terminology.hl7.org/CodeSystem/v3-ConceptGenerality                     // ConceptGenerality
Alias:   $v3-ConceptProperty                     = http://terminology.hl7.org/CodeSystem/v3-ConceptProperty                       // HL7 Value Set and Coded Concept Property Codes
Alias:   $v3-ConceptStatus                       = http://terminology.hl7.org/CodeSystem/v3-ConceptStatus                         // HL7 Coded Concept Status
Alias:   $v3-Confidentiality                     = http://terminology.hl7.org/CodeSystem/v3-Confidentiality                       // Confidentiality
Alias:   $v3-ContainerCap                        = http://terminology.hl7.org/CodeSystem/v3-ContainerCap                          // ContainerCap
Alias:   $v3-ContainerSeparator                  = http://terminology.hl7.org/CodeSystem/v3-ContainerSeparator                    // ContainerSeparator
Alias:   $v3-ContentProcessingMode               = http://terminology.hl7.org/CodeSystem/v3-ContentProcessingMode                 // ContentProcessingMode
Alias:   $v3-ContextControl                      = http://terminology.hl7.org/CodeSystem/v3-ContextControl                        // ContextControl
Alias:   $v3-Country                             = http://terminology.hl7.org/CodeSystem/v3-Country                               // Country
Alias:   $v3-cpt-4                               = http://www.ama-assn.org/go/cpt                                                 // CPT-4
Alias:   $v3-Currency                            = http://terminology.hl7.org/CodeSystem/v3-Currency                              // Currency
Alias:   $v3-DCM                                 = http://dicom.nema.org/resources/ontology/DCM                                   // DICOM Controlled Terminology
Alias:   $v3-DataOperation                       = http://terminology.hl7.org/CodeSystem/v3-DataOperation                         // DataOperation
Alias:   $v3-DataType                            = http://terminology.hl7.org/CodeSystem/v3-DataType                              // DataType
Alias:   $v3-dbSNP                               = http://www.ncbi.nlm.nih.gov/projects/SNP                                       // Genetic Sequence polymorphism database
Alias:   $v3-Dentition                           = http://terminology.hl7.org/CodeSystem/v3-Dentition                             // Dentition
Alias:   $v3-DeviceAlertLevel                    = http://terminology.hl7.org/CodeSystem/v3-DeviceAlertLevel                      // DeviceAlertLevel
Alias:   $v3-DocumentCompletion                  = http://terminology.hl7.org/CodeSystem/v3-DocumentCompletion                    // DocumentCompletion
Alias:   $v3-DocumentStorage                     = http://terminology.hl7.org/CodeSystem/v3-DocumentStorage                       // DocumentStorage
Alias:   $v3-EditStatus                          = http://terminology.hl7.org/CodeSystem/v3-EditStatus                            // EditStatus
Alias:   $v3-EducationLevel                      = http://terminology.hl7.org/CodeSystem/v3-EducationLevel                        // Education Level
Alias:   $v3-EmployeeJobClass                    = http://terminology.hl7.org/CodeSystem/v3-EmployeeJobClass                      // EmployeeJobClass
Alias:   $v3-EncounterAccident                   = http://terminology.hl7.org/CodeSystem/v3-EncounterAccident                     // EncounterAccident
Alias:   $v3-EncounterAcuity                     = http://terminology.hl7.org/CodeSystem/v3-EncounterAcuity                       // Encounter Acuity
Alias:   $v3-EncounterAdmissionSource            = http://terminology.hl7.org/CodeSystem/v3-EncounterAdmissionSource              // EncounterAdmissionSource
Alias:   $v3-EncounterReferralSource             = http://terminology.hl7.org/CodeSystem/v3-EncounterReferralSource               // EncounterReferralSource
Alias:   $v3-EncounterSpecialCourtesy            = http://terminology.hl7.org/CodeSystem/v3-EncounterSpecialCourtesy              // EncounterSpecialCourtesy
Alias:   $v3-EntityClass                         = http://terminology.hl7.org/CodeSystem/v3-EntityClass                           // EntityClass
Alias:   $v3-EntityCode                          = http://terminology.hl7.org/CodeSystem/v3-EntityCode                            // EntityCode
Alias:   $v3-EntityDeterminer                    = http://terminology.hl7.org/CodeSystem/v3-EntityDeterminer                      // EntityDeterminer
Alias:   $v3-EntityHandling                      = http://terminology.hl7.org/CodeSystem/v3-EntityHandling                        // EntityHandling
Alias:   $v3-EntityNamePartQualifier             = http://terminology.hl7.org/CodeSystem/v3-EntityNamePartQualifier               // EntityNamePartQualifier
Alias:   $v3-EntityNamePartQualifierR2           = http://terminology.hl7.org/CodeSystem/v3-EntityNamePartQualifierR2             // EntityNamePartQualifierR2
Alias:   $v3-EntityNamePartType                  = http://terminology.hl7.org/CodeSystem/v3-EntityNamePartType                    // EntityNamePartType
Alias:   $v3-EntityNamePartTypeR2                = http://terminology.hl7.org/CodeSystem/v3-EntityNamePartTypeR2                  // EntityNamePartTypeR2
Alias:   $v3-EntityNameUse                       = http://terminology.hl7.org/CodeSystem/v3-EntityNameUse                         // EntityNameUse
Alias:   $v3-EntityNameUseR2                     = http://terminology.hl7.org/CodeSystem/v3-EntityNameUseR2                       // EntityNameUseR2
Alias:   $v3-EntityRisk                          = http://terminology.hl7.org/CodeSystem/v3-EntityRisk                            // EntityRisk
Alias:   $v3-EntityStatus                        = http://terminology.hl7.org/CodeSystem/v3-EntityStatus                          // EntityStatus
Alias:   $v3-EquipmentAlertLevel                 = http://terminology.hl7.org/CodeSystem/v3-EquipmentAlertLevel                   // EquipmentAlertLevel
Alias:   $v3-Ethnicity                           = http://terminology.hl7.org/CodeSystem/v3-Ethnicity                             // Ethnicity
Alias:   $v3-ExposureMode                        = http://terminology.hl7.org/CodeSystem/v3-ExposureMode                          // ExposureMode
Alias:   $v3-fda-FCE                             = http://terminology.hl7.org/CodeSystem/v3-fda-FCE                               // Food and Drug Administration Food Canning Establishments
Alias:   $v3-fda-FFRN                            = http://terminology.hl7.org/CodeSystem/v3-fda-FFRN                              // Food and Drug Administration Food Facility Registration Numbers
Alias:   $v3-GTSAbbreviation                     = http://terminology.hl7.org/CodeSystem/v3-GTSAbbreviation                       // GTSAbbreviation
Alias:   $v3-GenderStatus                        = http://terminology.hl7.org/CodeSystem/v3-GenderStatus                          // GenderStatus
Alias:   $v3-HL7CommitteeIDInRIM                 = http://terminology.hl7.org/CodeSystem/v3-HL7CommitteeIDInRIM                   // HL7CommitteeIDInRIM
Alias:   $v3-HL7ConformanceInclusion             = http://terminology.hl7.org/CodeSystem/v3-HL7ConformanceInclusion               // HL7ConformanceInclusion
Alias:   $v3-HL7ContextConductionStyle           = http://terminology.hl7.org/CodeSystem/v3-HL7ContextConductionStyle             // HL7ContextConductionStyle
Alias:   $v3-HL7DefinedRoseProperty              = http://terminology.hl7.org/CodeSystem/v3-HL7DefinedRoseProperty                // HL7DefinedRoseProperty
Alias:   $v3-HL7StandardVersionCode              = http://terminology.hl7.org/CodeSystem/v3-HL7StandardVersionCode                // HL7StandardVersionCode
Alias:   $v3-HL7UpdateMode                       = http://terminology.hl7.org/CodeSystem/v3-HL7UpdateMode                         // HL7UpdateMode
Alias:   $v3-hc-AIC                              = http://www.canada.ca/en/health-canada/services/drugs-health-products/drug-products/drug-product-database-1 // Active Ingredient Code
Alias:   $v3-hc-AIGC                             = http://www.canada.ca/en/health-canada/services/drugs-health-products/drug-products/drug-product-database-2 // Active Ingredient Group Code
Alias:   $v3-hc-AIGN                             = http://www.canada.ca/en/health-canada/services/drugs-health-products/drug-products/drug-product-database-4 // Active Ingredient Group Number
Alias:   $v3-hc-DIN                              = http://www.canada.ca/en/health-canada/services/drugs-health-products/drug-products/drug-product-database-3 // Health Canada Drug Id Number
Alias:   $v3-hc-npn                              = http://hl7.org/fhir/sid/ca-hc-npn                                              // Health Canada Natural Product Number
Alias:   $v3-HealthcareProviderTaxonomyHIPAA     = http://terminology.hl7.org/CodeSystem/v3-HealthcareProviderTaxonomyHIPAA       // Healthcare Provider Taxonomy HIPAA
Alias:   $v3-hgnc                                = http://www.genenames.org                                                       // HUGO Gene Nomenclature
Alias:   $v3-hgvs                                = http://varnomen.hgvs.org                                                       // Human Genome Variation Society nomenclature
Alias:   $v3-hl7ApprovalStatus                   = http://terminology.hl7.org/CodeSystem/v3-hl7ApprovalStatus                     // HL7ApprovalStatus
Alias:   $v3-hl7CMETAttribution                  = http://terminology.hl7.org/CodeSystem/v3-hl7CMETAttribution                    // HL7CMETAttribution
Alias:   $v3-hl7ITSType                          = http://terminology.hl7.org/CodeSystem/v3-hl7ITSType                            // HL7ITSType
Alias:   $v3-hl7ITSVersionCode                   = http://terminology.hl7.org/CodeSystem/v3-hl7ITSVersionCode                     // HL7 ITS Version Code
Alias:   $v3-hl7PublishingDomain                 = http://terminology.hl7.org/CodeSystem/v3-hl7PublishingDomain                   // HL7PublishingDomain
Alias:   $v3-hl7PublishingSection                = http://terminology.hl7.org/CodeSystem/v3-hl7PublishingSection                  // HL7PublishingSection
Alias:   $v3-hl7PublishingSubSection             = http://terminology.hl7.org/CodeSystem/v3-hl7PublishingSubSection               // HL7PublishingSubSection
Alias:   $v3-hl7Realm                            = http://terminology.hl7.org/CodeSystem/v3-hl7Realm                              // HL7Realm
Alias:   $v3-hl7V3Conformance                    = http://terminology.hl7.org/CodeSystem/v3-hl7V3Conformance                      // HL7V3Conformance
Alias:   $v3-hl7VoteResolution                   = http://terminology.hl7.org/CodeSystem/v3-hl7VoteResolution                     // HL7VoteResolution
Alias:   $v3-HtmlLinkType                        = http://terminology.hl7.org/CodeSystem/v3-HtmlLinkType                          // HtmlLinkType
Alias:   $v3-ISO3166-1retired                    = http://terminology.hl7.org/CodeSystem/v3-ISO3166-1retired                      // ISO 3166 2 Character Country Codes
Alias:   $v3-ISO3166-2retired                    = http://terminology.hl7.org/CodeSystem/v3-ISO3166-2retired                      // ISO 3166 3 Character Country Codes
Alias:   $v3-ISO3166-3retired                    = http://terminology.hl7.org/CodeSystem/v3-ISO3166-3retired                      // ISO 3166 Numeric country Codes
Alias:   $v3-icpc                                = http://hl7.org/fhir/sid/icpc-1                                                 // International Classification of Primary Care, 1993 edition
Alias:   $v3-icpc2E                              = http://hl7.org/fhir/sid/icpc-2                                                 // International Classification of Primary Care, second edition (1998)
Alias:   $v3-IdentifierReliability               = http://terminology.hl7.org/CodeSystem/v3-IdentifierReliability                 // IdentifierReliability
Alias:   $v3-IdentifierScope                     = http://terminology.hl7.org/CodeSystem/v3-IdentifierScope                       // IdentifierScope
Alias:   $v3-ietf3066                            = urn:ietf:bcp:47                                                                // Tags for the Identification of Languages
Alias:   $v3-IntegrityCheckAlgorithm             = http://terminology.hl7.org/CodeSystem/v3-IntegrityCheckAlgorithm               // IntegrityCheckAlgorithm
Alias:   $v3-iso3166-2                           = urn:iso:std:iso:3166:-2                                                        // ISO 3166 Part 2 Country Subdivision Codes
Alias:   $v3-iso4217-HL7                         = http://terminology.hl7.org/CodeSystem/v3-iso4217-HL7                           // ISO 4217 Currency code, HL7 use
Alias:   $v3-loinc                               = http://loinc.org                                                               // Logical Observation Identifiers, Names and Codes (LOINC)
Alias:   $v3-LanguageAbilityMode                 = http://terminology.hl7.org/CodeSystem/v3-LanguageAbilityMode                   // LanguageAbilityMode
Alias:   $v3-LanguageAbilityProficiency          = http://terminology.hl7.org/CodeSystem/v3-LanguageAbilityProficiency            // LanguageAbilityProficiency
Alias:   $v3-LivingArrangement                   = http://terminology.hl7.org/CodeSystem/v3-LivingArrangement                     // LivingArrangement
Alias:   $v3-LocalMarkupIgnore                   = http://terminology.hl7.org/CodeSystem/v3-LocalMarkupIgnore                     // LocalMarkupIgnore
Alias:   $v3-LocalRemoteControlState             = http://terminology.hl7.org/CodeSystem/v3-LocalRemoteControlState               // LocalRemoteControlState
Alias:   $v3-lrg                                 = http://www.lrg-sequence.org                                                    // Locus Reference Genomic Sequences (LRG)
Alias:   $v3-MDFAttributeType                    = http://terminology.hl7.org/CodeSystem/v3-MDFAttributeType                      // MDFAttributeType
Alias:   $v3-MDFSubjectAreaPrefix                = http://terminology.hl7.org/CodeSystem/v3-MDFSubjectAreaPrefix                  // MDFSubjectAreaPrefix
Alias:   $v3-ManagedParticipationStatus          = http://terminology.hl7.org/CodeSystem/v3-ManagedParticipationStatus            // ManagedParticipationStatus
Alias:   $v3-MapRelationship                     = http://terminology.hl7.org/CodeSystem/v3-MapRelationship                       // MapRelationship
Alias:   $v3-MaritalStatus                       = http://terminology.hl7.org/CodeSystem/v3-MaritalStatus                         // MaritalStatus
Alias:   $v3-MaterialForm                        = http://terminology.hl7.org/CodeSystem/v3-MaterialForm                          // MaterialForm
Alias:   $v3-MaterialType                        = http://terminology.hl7.org/CodeSystem/v3-MaterialType                          // MaterialType
Alias:   $v3-mdc                                 = urn:iso:std:iso:11073:10101                                                    // ISO 11073-10101 Health informatics - Point-of-care
Alias:   $v3-MdfHmdMetSourceType                 = http://terminology.hl7.org/CodeSystem/v3-MdfHmdMetSourceType                   // MdfHmdMetSourceType
Alias:   $v3-MdfHmdRowType                       = http://terminology.hl7.org/CodeSystem/v3-MdfHmdRowType                         // MdfHmdRowType
Alias:   $v3-MdfRmimRowType                      = http://terminology.hl7.org/CodeSystem/v3-MdfRmimRowType                        // MdfRmimRowType
Alias:   $v3-mediaType                           = http://terminology.hl7.org/CodeSystem/v3-mediaType                             // Media Type
Alias:   $v3-MessageCondition                    = http://terminology.hl7.org/CodeSystem/v3-MessageCondition                      // MessageCondition
Alias:   $v3-MessageWaitingPriority              = http://terminology.hl7.org/CodeSystem/v3-MessageWaitingPriority                // MessageWaitingPriority
Alias:   $v3-mime                                = http://www.iana.org/assignments/media-types                                    // MIME
Alias:   $v3-ModifyIndicator                     = http://terminology.hl7.org/CodeSystem/v3-ModifyIndicator                       // ModifyIndicator
Alias:   $v3-nciThesaurus                        = http://ncithesaurus-stage.nci.nih.gov                                          // NCI Thesaurus
Alias:   $v3-ndc                                 = http://hl7.org/fhir/sid/ndc                                                    // National drug codes
Alias:   $v3-nuccProviderCodes                   = http://terminology.hl7.org/CodeSystem/v3-nuccProviderCodes                     // NUCC Health Care Provider Taxonomy
Alias:   $v3-NullFlavor                          = http://terminology.hl7.org/CodeSystem/v3-NullFlavor                            // NullFlavor
Alias:   $v3-ObservationCategory                 = http://terminology.hl7.org/CodeSystem/v3-ObservationCategory                   // ObservationCategory
Alias:   $v3-ObservationInterpretation           = http://terminology.hl7.org/CodeSystem/v3-ObservationInterpretation             // ObservationInterpretation
Alias:   $v3-ObservationMethod                   = http://terminology.hl7.org/CodeSystem/v3-ObservationMethod                     // ObservationMethod
Alias:   $v3-ObservationValue                    = http://terminology.hl7.org/CodeSystem/v3-ObservationValue                      // ObservationValue
Alias:   $v3-orderableDrugForm                   = http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm                     // Orderable Drug Form
Alias:   $v3-OrganizationNameType                = http://terminology.hl7.org/CodeSystem/v3-OrganizationNameType                  // OrganizationNameType
Alias:   $v3-ParameterizedDataType               = http://terminology.hl7.org/CodeSystem/v3-ParameterizedDataType                 // ParameterizedDataType
Alias:   $v3-ParticipationFunction               = http://terminology.hl7.org/CodeSystem/v3-ParticipationFunction                 // ParticipationFunction
Alias:   $v3-ParticipationMode                   = http://terminology.hl7.org/CodeSystem/v3-ParticipationMode                     // ParticipationMode
Alias:   $v3-ParticipationSignature              = http://terminology.hl7.org/CodeSystem/v3-ParticipationSignature                // ParticipationSignature
Alias:   $v3-ParticipationType                   = http://terminology.hl7.org/CodeSystem/v3-ParticipationType                     // ParticipationType
Alias:   $v3-PatientImportance                   = http://terminology.hl7.org/CodeSystem/v3-PatientImportance                     // PatientImportance
Alias:   $v3-PaymentTerms                        = http://terminology.hl7.org/CodeSystem/v3-PaymentTerms                          // PaymentTerms
Alias:   $v3-PeriodicIntervalOfTimeAbbreviation  = http://terminology.hl7.org/CodeSystem/v3-PeriodicIntervalOfTimeAbbreviation    // PeriodicIntervalOfTimeAbbreviation
Alias:   $v3-PersonDisabilityType                = http://terminology.hl7.org/CodeSystem/v3-PersonDisabilityType                  // PersonDisabilityType
Alias:   $v3-PostalAddressUse                    = http://terminology.hl7.org/CodeSystem/v3-PostalAddressUse                      // PostalAddressUse
Alias:   $v3-ProbabilityDistributionType         = http://terminology.hl7.org/CodeSystem/v3-ProbabilityDistributionType           // ProbabilityDistributionType
Alias:   $v3-ProcessingID                        = http://terminology.hl7.org/CodeSystem/v3-ProcessingID                          // ProcessingID
Alias:   $v3-ProcessingMode                      = http://terminology.hl7.org/CodeSystem/v3-ProcessingMode                        // ProcessingMode
Alias:   $v3-QueryParameterValue                 = http://terminology.hl7.org/CodeSystem/v3-QueryParameterValue                   // QueryParameterValue
Alias:   $v3-QueryPriority                       = http://terminology.hl7.org/CodeSystem/v3-QueryPriority                         // QueryPriority
Alias:   $v3-QueryQuantityUnit                   = http://terminology.hl7.org/CodeSystem/v3-QueryQuantityUnit                     // QueryQuantityUnit
Alias:   $v3-QueryRequestLimit                   = http://terminology.hl7.org/CodeSystem/v3-QueryRequestLimit                     // QueryRequestLimit
Alias:   $v3-QueryResponse                       = http://terminology.hl7.org/CodeSystem/v3-QueryResponse                         // QueryResponse
Alias:   $v3-QueryStatusCode                     = http://terminology.hl7.org/CodeSystem/v3-QueryStatusCode                       // QueryStatusCode
Alias:   $v3-Race                                = http://terminology.hl7.org/CodeSystem/v3-Race                                  // Race
Alias:   $v3-refSeq                              = http://www.ncbi.nlm.nih.gov/refseq                                             // Gene Reference Sequence Collection
Alias:   $v3-RelationalOperator                  = http://terminology.hl7.org/CodeSystem/v3-RelationalOperator                    // RelationalOperator
Alias:   $v3-RelationshipConjunction             = http://terminology.hl7.org/CodeSystem/v3-RelationshipConjunction               // RelationshipConjunction
Alias:   $v3-ReligiousAffiliation                = http://terminology.hl7.org/CodeSystem/v3-ReligiousAffiliation                  // Religious Affiliation
Alias:   $v3-ResponseLevel                       = http://terminology.hl7.org/CodeSystem/v3-ResponseLevel                         // ResponseLevel
Alias:   $v3-ResponseModality                    = http://terminology.hl7.org/CodeSystem/v3-ResponseModality                      // ResponseModality
Alias:   $v3-ResponseMode                        = http://terminology.hl7.org/CodeSystem/v3-ResponseMode                          // ResponseMode
Alias:   $v3-RoleClass                           = http://terminology.hl7.org/CodeSystem/v3-RoleClass                             // RoleClass
Alias:   $v3-RoleCode                            = http://terminology.hl7.org/CodeSystem/v3-RoleCode                              // RoleCode
Alias:   $v3-RoleLinkStatus                      = http://terminology.hl7.org/CodeSystem/v3-RoleLinkStatus                        // RoleLinkStatus
Alias:   $v3-RoleLinkType                        = http://terminology.hl7.org/CodeSystem/v3-RoleLinkType                          // RoleLinkType
Alias:   $v3-RoleStatus                          = http://terminology.hl7.org/CodeSystem/v3-RoleStatus                            // RoleStatus
Alias:   $v3-RouteOfAdministration               = http://terminology.hl7.org/CodeSystem/v3-RouteOfAdministration                 // RouteOfAdministration
Alias:   $v3-rxNorm                              = http://www.nlm.nih.gov/research/umls/rxnorm                                    // RxNorm
Alias:   $v3-snomed-CT                           = http://snomed.info/sct                                                         // SNOMEDÂ CT International Edition
Alias:   $v3-scpqual                             = https://fhir.infoway-inforoute.ca/CodeSystem/scpqual                           // pan-Canadian Provider Qualification Types
Alias:   $v3-scptype                             = https://fhir.infoway-inforoute.ca/CodeSystem/scptype                           // pan-Canadian Provider Types
Alias:   $v3-sctemp                              = https://fhir.infoway-inforoute.ca/CodeSystem/sctemp                            // pan-Canadian Temporary Codes
Alias:   $v3-Sequencing                          = http://terminology.hl7.org/CodeSystem/v3-Sequencing                            // Sequencing
Alias:   $v3-SetOperator                         = http://terminology.hl7.org/CodeSystem/v3-SetOperator                           // SetOperator
Alias:   $v3-SpecimenType                        = http://terminology.hl7.org/CodeSystem/v3-SpecimenType                          // SpecimenType
Alias:   $v3-styleType                           = http://terminology.hl7.org/CodeSystem/v3-styleType                             // Style Type
Alias:   $v3-substanceAdminSubstitution          = http://terminology.hl7.org/CodeSystem/v3-substanceAdminSubstitution            // Substance Admin Substitution
Alias:   $v3-SubstitutionCondition               = http://terminology.hl7.org/CodeSystem/v3-SubstitutionCondition                 // SubstitutionCondition
Alias:   $v3-TableCellHorizontalAlign            = http://terminology.hl7.org/CodeSystem/v3-TableCellHorizontalAlign              // TableCellHorizontalAlign
Alias:   $v3-TableCellScope                      = http://terminology.hl7.org/CodeSystem/v3-TableCellScope                        // TableCellScope
Alias:   $v3-TableCellVerticalAlign              = http://terminology.hl7.org/CodeSystem/v3-TableCellVerticalAlign                // TableCellVerticalAlign
Alias:   $v3-TableFrame                          = http://terminology.hl7.org/CodeSystem/v3-TableFrame                            // TableFrame
Alias:   $v3-TableRules                          = http://terminology.hl7.org/CodeSystem/v3-TableRules                            // TableRules
Alias:   $v3-TargetAwareness                     = http://terminology.hl7.org/CodeSystem/v3-TargetAwareness                       // TargetAwareness
Alias:   $v3-TelecommunicationAddressUse         = http://terminology.hl7.org/CodeSystem/v3-TelecommunicationAddressUse           // TelecommunicationAddressUse
Alias:   $v3-TelecommunicationCapabilities       = http://terminology.hl7.org/CodeSystem/v3-TelecommunicationCapabilities         // TelecommunicationCapabilities
Alias:   $v3-TimingEvent                         = http://terminology.hl7.org/CodeSystem/v3-TimingEvent                           // TimingEvent
Alias:   $v3-TransmissionRelationshipTypeCode    = http://terminology.hl7.org/CodeSystem/v3-TransmissionRelationshipTypeCode      // TransmissionRelationshipTypeCode
Alias:   $v3-TribalEntityUS                      = http://terminology.hl7.org/CodeSystem/v3-TribalEntityUS                        // TribalEntityUS
Alias:   $v3-ucum                                = http://unitsofmeasure.org                                                      // Unified Code for Units of Measure (UCUM)
Alias:   $v3-URLScheme                           = http://terminology.hl7.org/CodeSystem/v3-URLScheme                             // Universal Resource Locator Scheme
Alias:   $v3-VaccineManufacturer                 = http://terminology.hl7.org/CodeSystem/v3-VaccineManufacturer                   // VaccineManufacturer
Alias:   $v3-VaccineType                         = http://terminology.hl7.org/CodeSystem/v3-VaccineType                           // VaccineType
Alias:   $v3-VocabularyDomainQualifier           = http://terminology.hl7.org/CodeSystem/v3-VocabularyDomainQualifier             // VocabularyDomainQualifier
Alias:   $v3-WC                                  = http://www.whocc.no/atc                                                        // WHO ATC
Alias:   $v3-WorkClassificationODH               = http://terminology.hl7.org/CodeSystem/v3-WorkClassificationODH                 // Work Classification (Occupational Data for Health)
