# This workflow will build the index.json file, then push the change to the main branch

name: Build Action

on:
  pull_request_target:
    branches:
      - main

jobs:
  build:

    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [12.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{github.event.pull_request.head.ref}}
        repository: ${{github.event.pull_request.head.repo.full_name}}
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build
    - run: git config --local user.name  ${{ github.actor }}
    - run: git add index.json
    - run: git commit -m "Automatic manifest update"
    - name: 
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{github.event.pull_request.head.ref}}
        force: true

